### ISSUE TITLE
Bread & Water not being deposited in house and stash inventory

### ISSUE THREAD

**Issue by KoolAiddTV** [chrisrogersukgb/lsrp-motels#8]
Whenever I try to desposit any bread/water item into the stash or the room inventory it takes it out of my pocket and doesn't show up on the stash inventory

**Comment by FrankieM8** [comment]
works fine for me

**Comment by 85Compacom** [comment]
same here if you can find solution would be really good

**Comment by KoolAiddTV** [comment]
Resolved live-internal.fivem.net:30110 to 178.32.9.100:30110 
Creating script environments for _cfx_internal 
Found new resource esx_addons_gcphone in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_addons_gcphone 
Found new resource fivem-map-skater in /home/zap406066/g109518/gta5-fivem/server-data/resources//fivem-map-skater 
Found new resource esx_carlock in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_carlock 
Found new resource esx_mugging in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_mugging 
Found new resource legacyfuel in /home/zap406066/g109518/gta5-fivem/server-data/resources//legacyfuel 
Found new resource npcweapons in /home/zap406066/g109518/gta5-fivem/server-data/resources//npcweapons 
Found new resource esx_advancedgarage in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_advancedgarage 
Found new resource PillboxHospital in /home/zap406066/g109518/gta5-fivem/server-data/resources//PillboxHospital 
Found new resource eup-ui in /home/zap406066/g109518/gta5-fivem/server-data/resources//eup-ui 
Found new resource fivem-map-hipster in /home/zap406066/g109518/gta5-fivem/server-data/resources//fivem-map-hipster 
Found new resource esx_sit in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_sit 
Found new resource Weaponry in /home/zap406066/g109518/gta5-fivem/server-data/resources//Weaponry 
Found new resource esx_drp_garage in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_drp_garage 
Found new resource calmai in /home/zap406066/g109518/gta5-fivem/server-data/resources//calmai 
Found new resource esx_inventoryhud_trunk in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_inventoryhud_trunk 
Found new resource esx_phone3 in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_phone3 
Found new resource esx_weaponshop in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_weaponshop 
Resource loading for esx_weaponshop failed: 
Could not open resource metadata file /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_weaponshop/__resource.lua. 
Found new resource gcphone in /home/zap406066/g109518/gta5-fivem/server-data/resources//gcphone 
Found new resource esx_weashops in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_weashops 
Found new resource carhud in /home/zap406066/g109518/gta5-fivem/server-data/resources//carhud 
Found new resource pNotify in /home/zap406066/g109518/gta5-fivem/server-data/resources//pNotify 
Found new resource esx-kr-vehicle-push in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx-kr-vehicle-push 
Found new resource esx_voice in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_voice 
Found new resource esx_duty in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_duty 
Found new resource esx_aiomenu in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_aiomenu 
Found new resource esx_status in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_status
Found new resource police in /home/zap406066/g109518/gta5-fivem/server-data/resources//police 
Found new resource esx_SodaMachine in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_SodaMachine 
Found new resource shops in /home/zap406066/g109518/gta5-fivem/server-data/resources//shops 
Found new resource mysql-async in /home/zap406066/g109518/gta5-fivem/server-data/resources//mysql-async 
Found new resource esx_plasticsurgery in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_plasticsurgery 
Found new resource vehiclecommands in /home/zap406066/g109518/gta5-fivem/server-data/resources//vehiclecommands 
Found new resource FiveM-Clothes in /home/zap406066/g109518/gta5-fivem/server-data/resources//FiveM-Clothes 
Found new resource mythic_progbar in /home/zap406066/g109518/gta5-fivem/server-data/resources//mythic_progbar 
Found new resource runcode in /home/zap406066/g109518/gta5-fivem/server-data/resources//runcode 
Found new resource esx_kashacters in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_kashacters 
Found new resource simpleinteractions in /home/zap406066/g109518/gta5-fivem/server-data/resources//simpleinteractions 
Found new resource bob74_ipl in /home/zap406066/g109518/gta5-fivem/server-data/resources//bob74_ipl 
Found new resource fs_taxi in /home/zap406066/g109518/gta5-fivem/server-data/resources//fs_taxi 
Found new resource es_admin2 in /home/zap406066/g109518/gta5-fivem/server-data/resources//es_admin2
Found new resource eup-stream in /home/zap406066/g109518/gta5-fivem/server-data/resources//eup-stream 
Found new resource doorlocks in /home/zap406066/g109518/gta5-fivem/server-data/resources//doorlocks 
Found new resource tackle in /home/zap406066/g109518/gta5-fivem/server-data/resources//tackle 
Found new resource healthnotincar in /home/zap406066/g109518/gta5-fivem/server-data/resources//healthnotincar 
Found new resource vMenu in /home/zap406066/g109518/gta5-fivem/server-data/resources//vMenu 
Found new resource esplugin_mysql in /home/zap406066/g109518/gta5-fivem/server-data/resources//esplugin_mysql 
Found new resource PvP in /home/zap406066/g109518/gta5-fivem/server-data/resources//PvP 
Found new resource essentialmode in /home/zap406066/g109518/gta5-fivem/server-data/resources//essentialmode 
Found new resource fivem-awesome1501 in /home/zap406066/g109518/gta5-fivem/server-data/resources//fivem-awesome1501 
Found new resource JF_SeatShuffle in /home/zap406066/g109518/gta5-fivem/server-data/resources//JF_SeatShuffle 
Found new resource esx-kr-advanced-shops in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx-kr-advanced-shops 
Found new resource emotes in /home/zap406066/g109518/gta5-fivem/server-data/resources//emotes 
Found new resource esx_healthbar in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_healthbar 
Found new resource fivem in /home/zap406066/g109518/gta5-fivem/server-data/resources//fivem 
Found new resource esx_mechanicjobb in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_mechanicjobb 
Resource loading for esx_mechanicjobb failed: 
Could not open resource metadata file /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_mechanicjobb/__resource.lua. 
Found new resource removeAIcops in /home/zap406066/g109518/gta5-fivem/server-data/resources//removeAIcops 
Found new resource esx_hospital in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_hospital 
Found new resource es_ui in /home/zap406066/g109518/gta5-fivem/server-data/resources//es_ui 
Found new resource ghmattimysql in /home/zap406066/g109518/gta5-fivem/server-data/resources//ghmattimysql 
Found new resource JoinTransition in /home/zap406066/g109518/gta5-fivem/server-data/resources//JoinTransition 
Found new resource RealisticVehicleFailure in /home/zap406066/g109518/gta5-fivem/server-data/resources//RealisticVehicleFailure 
Found new resource NativeUI in /home/zap406066/g109518/gta5-fivem/server-data/resources//NativeUI 
Found new resource esx_clip in /home/zap406066/g109518/gta5-fivem/server-data/resources//esx_clip 
Found new resource wk_wrs in /home/zap406066/g109518/gta5-fivem/server-data/resources//wk_wrs 
Found new resource mapmanager in /home/zap406066/g109518/gta5-fivem/server-data/resources//[managers]/mapmanager 
Found new resource race-test in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gamemodes]/race-test 
Found new resource race in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gamemodes]/race 
Found new resource scoreboard in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/scoreboard 
Found new resource chat-theme-gtao in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/chat-theme-gtao 
Found new resource baseevents in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/baseevents 
Found new resource hardcap in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/hardcap 
Found new resource spawnmanager in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/spawnmanager 
Found new resource sessionmanager in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/sessionmanager 
Found new resource chat in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/chat 
Found new resource rconlog in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/rconlog 
Found new resource esx_license in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_license 
Found new resource esx_addoninventory in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_addoninventory 
Found new resource esx_clotheshop in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_clotheshop 
Found new resource esx_jobs in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_jobs 
Found new resource esx_whitelist in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_whitelist 
Found new resource esx_holdup in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_holdup 
Found new resource esx_identity in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_identity 
Found new resource new_banking in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/new_banking 
Found new resource esx_randomevents in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_randomevents 
Resource loading for esx_randomevents failed: 
Could not open resource metadata file /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_randomevents/__resource.lua. 
Found new resource esx_menu_dialog in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_menu_dialog 
Found new resource esx_optionalneeds in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_optionalneeds 
Found new resource esx_garage in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_garage 
Found new resource esx_boat in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_boat 
Found new resource esx_voicevanilla in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_voicevanilla 
Found new resource esx_bankerjob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_bankerjob 
Found new resource gsrtest in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/gsrtest 
Found new resource es_camera in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/es_camera 
Found new resource esx_migrate in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_migrate 
Found new resource esx_datastore in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_datastore 
Found new resource esx_drugs in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_drugs 
Found new resource cron in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/cron 
Found new resource esx_boilerplate in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_boilerplate 
Found new resource instance in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/instance 
Found new resource esx_ambulancejob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_ambulancejob 
Found new resource esx_accessories in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_accessories 
Found new resource esx_property in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_property 
Found new resource esx_phone in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_phone 
Found new resource esx_supermarket in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_supermarket 
Found new resource esx_menu_list in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_menu_list 
Found new resource esx_joblisting in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_joblisting 
Found new resource esx_taxijob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_taxijob 
Found new resource esx_barbershop in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_barbershop 
Found new resource esx_menu_default in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_menu_default 
Found new resource esx_vehicleshop in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_vehicleshop 
Found new resource esx_mechanicjob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_mechanicjob 
Found new resource esx_service in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_service 
Found new resource esx_rpchat in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_rpchat 
Found new resource esx_addonaccount in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_addonaccount 
Found new resource esx_realestateagentjob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_realestateagentjob 
Found new resource esx_billing in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_billing 
Found new resource esx_inventoryhud in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_inventoryhud 
Found new resource es_extended in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/es_extended 
Found new resource esx_basicneeds in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_basicneeds 
Found new resource esx_lscustom in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_lscustom 
Found new resource esx_policejob in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_policejob 
Found new resource esx_shops in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_shops 
Found new resource esx_cruisecontrol in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_cruisecontrol 
Found new resource skinchanger in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/skinchanger 
Found new resource esx_skin in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_skin 
Found new resource lsrp-motels in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/lsrp-motels 
Found new resource esx_society in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_society 
Found new resource esx_whitelistEnhanced in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_whitelistEnhanced 
Found new resource esx_weaponshopvanilla in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_weaponshopvanilla 
Found new resource async in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/async 
Found new resource esx_atm in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_atm 
Found new resource esx_dmvschool in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_dmvschool 
Found new resource esx_animations in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_animations 
Found new resource esx_gsr in /home/zap406066/g109518/gta5-fivem/server-data/resources//[esx]/esx_gsr 
Found new resource irc in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gameplay]/irc 
Found new resource playernames in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gameplay]/playernames 
Found new resource obituary-deaths in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gameplay]/obituary-deaths 
Found new resource obituary in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gameplay]/obituary 
Found new resource channelfeed in /home/zap406066/g109518/gta5-fivem/server-data/resources//[gameplay]/channelfeed 
Found new resource gameInit in /home/zap406066/g109518/gta5-fivem/server-data/resources//[test]/gameInit 
Found new resource betaguns in /home/zap406066/g109518/gta5-fivem/server-data/resources//[test]/betaguns 
Found new resource keks in /home/zap406066/g109518/gta5-fivem/server-data/resources//[test]/keks 
Found new resource yarn in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/[builders]/yarn 
Found new resource webpack in /home/zap406066/g109518/gta5-fivem/server-data/resources//[system]/[builders]/webpack 
Creating script environments for sessionmanager 
Started resource sessionmanager 
Creating script environments for mapmanager 
Started resource mapmanager 
Creating script environments for chat 
Started resource chat 
Started resource spawnmanager 
Started gametype Freeroam 
Started resource fivem 
Creating script environments for hardcap 
Started resource hardcap 
Creating script environments for rconlog 
Started resource rconlog 
Started resource scoreboard 
Creating script environments for vMenu 
Loaded vMenuShared.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1615174449 
Loaded vMenuServer.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1615174449 
Instantiated instance of script GHMatti.Http.RequestInternal. 
Instantiated instance of script GHMatti.Http.Request. 
Instantiated instance of script vMenuServer.BanManager. 
Instantiated instance of script vMenuServer.MainServer. 
Instantiated instance of script vMenuServer.UpdateChecker. 
Started resource vMenu 
Creating script environments for mysql-async 
Loaded MySQLAsync.net, Version=2.1.1.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_1277999674 
Instantiated instance of script MySQLAsync.MySQLThread. 
Instantiated instance of script MySQLAsync.MySQLAsync. 
Started resource mysql-async 
Creating script environments for essentialmode 
Loaded SQLite.net, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_20854607 
Instantiated instance of script SQLite.Main. 
Started resource essentialmode 
Creating script environments for esplugin_mysql 
Started resource esplugin_mysql 
Creating script environments for es_admin2 
Started resource es_admin2 
Creating script environments for async 
Started resource async 
Creating script environments for cron 
Started resource cron 
Creating script environments for es_extended 
Started resource es_extended 
Creating script environments for instance 
Started resource instance 
Creating script environments for es_camera 
Started resource es_camera 
Started resource skinchanger 
Creating script environments for esx_skin 
Started resource esx_skin 
Started resource PvP 
Creating script environments for esx_addonaccount 
Started resource esx_addonaccount 
Creating script environments for esx_society 
Started resource esx_society 
Creating script environments for esx_addoninventory 
Started resource esx_addoninventory 
Creating script environments for esx_vehicleshop 
Started resource esx_vehicleshop 
Creating script environments for esx_ambulancejob 
Started resource esx_ambulancejob 
Started resource esx_animations 
Creating script environments for esx_barbershop 
Started resource esx_barbershop 
Creating script environments for esx_status 
Started resource esx_status 
Creating script environments for esx_basicneeds 
Started resource esx_basicneeds 
Creating script environments for esx_boat 
Started resource esx_boat 
Creating script environments for FiveM-Clothes 
Started resource FiveM-Clothes 
Started resource esx_cruisecontrol 
Creating script environments for esx_datastore 
Started resource esx_datastore 
Creating script environments for esx_drugs 
Started resource esx_drugs 
Started resource carhud 
Creating script environments for esx_addons_gcphone 
Started resource esx_addons_gcphone 
Creating script environments for gcphone 
Started resource gcphone 
Creating script environments for fs_taxi 
Started resource fs_taxi 
Creating script environments for esx_holdup 
Started resource esx_holdup 
Creating script environments for esx_kashacters 
Started resource esx_kashacters 
Creating script environments for esx_identity 
Started resource esx_identity 
Creating script environments for esx_joblisting 
Started resource esx_joblisting 
Creating script environments for esx_jobs 
Started resource esx_jobs 
Creating script environments for esx_license 
Started resource esx_license 
Creating script environments for esx_lscustom 
Started resource esx_lscustom 
Started resource esx_menu_default 
Started resource esx_menu_dialog 
Started resource esx_menu_list 
Creating script environments for esx_billing 
Started resource esx_billing 
Creating script environments for esx_policejob 
==== Enregistrement du telephone police => Police alert 
Started resource esx_policejob 
Creating script environments for esx_property 
Started resource esx_property 
Creating script environments for esx_rpchat 
Started resource esx_rpchat 
Creating script environments for esx_service 
Started resource esx_service 
Creating script environments for esx_sit 
Started resource esx_sit 
Creating script environments for esx_taxijob 
==== Enregistrement du telephone taxi => Taxi Client 
Started resource esx_taxijob 
Started resource esx_voice 
[93mCouldn't find resource esx_weashop.[0m 
Creating script environments for esx_clip 
Started resource esx_clip 
Started resource mythic_progbar 
Creating script environments for esx_mugging 
Started resource esx_mugging 
Started resource pNotify 
Creating script environments for esx_inventoryhud 
Started resource esx_inventoryhud 
Creating script environments for esx_inventoryhud_trunk 
Started resource esx_inventoryhud_trunk 
Creating script environments for esx_drp_garage 
Started resource esx_drp_garage 
Creating script environments for new_banking 
Started resource new_banking 
Started resource healthnotincar 
Started resource Weaponry 
Started resource bob74_ipl 
Creating script environments for esx_hospital 
Started resource esx_hospital 
Started resource PillboxHospital 
Creating script environments for legacyfuel 
Started resource legacyfuel 
Creating script environments for esx_carlock 
Started resource esx_carlock 
Creating script environments for esx_aiomenu 
Started resource esx_aiomenu 
Started resource vehiclecommands 
Started resource esx-kr-vehicle-push 
Creating script environments for RealisticVehicleFailure 
Started resource RealisticVehicleFailure 
Creating script environments for doorlocks 
Started resource doorlocks 
Started resource wk_wrs 
Creating script environments for tackle 
Started resource tackle 
Creating script environments for gsrtest 
Started resource gsrtest 
Creating script environments for esx_gsr 
Started resource esx_gsr 
Started resource simpleinteractions 
Started resource emotes 
Started resource npcweapons 
Started resource removeAIcops 
Started resource NativeUI 
Creating script environments for ghmattimysql 
Started resource ghmattimysql 
Creating script environments for esx_supermarket 
Started resource esx_supermarket 
Started resource JF_SeatShuffle 
Creating script environments for esx_plasticsurgery 
Started resource esx_plasticsurgery 
Creating script environments for calmai 
CalmAI Loaded. AI is now Relaxed! Coded by NickThe0ne 
Started resource calmai 
Started resource eup-stream 
Started resource eup-ui 
Creating script environments for lsrp-motels 
Started resource lsrp-motels 
Started resource es_ui 
Stopping resource sessionmanager 
Creating script environments for sessionmanager 
Started resource sessionmanager 
Authenticating server license key... 
Server license key authentication succeeded. Welcome! 
cfx> Sending heartbeat to live-internal.fivem.net:30110 
Performing version check against: https://api.kanersps.pw/em/version?version=6.2.1&uuid=1bd91251-1416-4cf9-4138-716372298129 

Started map fivem-map-skater 
Started resource fivem-map-skater 
server thread hitch warning: timer interval of 627 milliseconds 

[EssentialMode] Current version: 6.2.1 
[EssentialMode] Updater version: 

Access denied for command sets. 
Access denied for command sets. 
[EssentialMode] Everything is nice and updated! 



[36m[vMenu] Checking for updates.[0m 
[36m[vMenu] [93mA new version of vMenu (v3.0.3) is available if you manually install it ([36mhttps://github.com/TomGrobbe/vMenu/releases/v3.0.3[93m). 
[36m[vMenu] [93mThe ZAP-Hosting one-click-installer version will be updated by ZAP-Hosting support as soon as possible, please be patient. Please do not spam ZAP-Hosting support for an ETA, thanks![0m For info and support: www.vespura.com. Discord: www.vespura.com/discord.[97m 
[32m[vMenu] Your version of vMenu is up to date! Good job![0m 

server thread hitch warning: timer interval of 429 milliseconds 
Connecting: KillerKoolAidd[0m 
Connecting: 9 Fingers Deep[0m 
Sending heartbeat to live-internal.fivem.net:30110 
Sending heartbeat to live-internal.fivem.net:30110 
pcm25 
server thread hitch warning: timer interval of 440 milliseconds 
pcm26 
pcm26 
Error running call reference function for resource esx_addoninventory: citizen:/scripting/lua/scheduler.lua:405: @esx_addoninventory/server/classes/addoninventory.lua:39: attempt to index a nil value (global 'Items') 
stack traceback: 
@esx_addoninventory/server/classes/addoninventory.lua:39: in field 'getItem' 
@esx_addoninventory/server/classes/addoninventory.lua:9: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374> 
[C]: in function 'coroutine.resume' 
citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182> 
Error running call reference function for resource lsrp-motels: citizen:/scripting/lua/scheduler.lua:405: citizen:/scripting/lua/MessagePack.lua:830: missing bytes 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow' 
citizen:/scripting/lua/MessagePack.lua:465: in field 'any' 
citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack' 
citizen:/scripting/lua/scheduler.lua:628: in field 'addItem' 
@lsrp-motels/server/server.lua:143: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:391: in function <citizen:/scripting/lua/scheduler.lua:390> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:390: in function <citizen:/scripting/lua/scheduler.lua:389> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:405: in function <citizen:/scripting/lua/scheduler.lua:374> 
[C]: in function 'coroutine.resume' 
citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182> 
Error running system event handling function for resource esx_addoninventory: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow' 
citizen:/scripting/lua/MessagePack.lua:465: in field 'any' 
citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack' 
citizen:/scripting/lua/scheduler.lua:628: in local 'cb' 
@esx_addoninventory/server/main.lua:82: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:219: in function <citizen:/scripting/lua/scheduler.lua:218> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow' 
citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182> 
server thread hitch warning: timer interval of 418 milliseconds 
pcm26 
server thread hitch warning: timer interval of 475 milliseconds
 

This is what I'm getting in my console when I try to deposit an item.

**Comment by vslash234** [comment]
zzzzzzzZZZz try to search before spam anything.

go to resources/esx_addoninventory/server/main.lua and change the 1st and 2nd line for this:

```
Items = {}
local InventoriesIndex, Inventories, SharedInventories = {}, {}, {}
```

You're welcome

**Comment by KoolAiddTV** [comment]
> zzzzzzzZZZz try to search before spam anything.
> 
> go to resources/esx_addoninventory/server/main.lua and change the 1st and 2nd line for this:
> 
> ```
> Items = {}
> local InventoriesIndex, Inventories, SharedInventories = {}, {}, {}
> ```
> 
> You're welcome

Thank you for helping. It fixed it
